name: Update JSON from Issues
on:
    issues:
        types: [opened]
jobs:
    update-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Parse Issue
              id: parse
              run: |
                echo "ISSUE_BODY=$(jq -r '.issue.body' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
            - name: Update JSON
              run: |
                echo '[]' > data.json  # 初始化或保留原有数据
                jq --arg author "$(echo "$ISSUE_BODY" | grep '作者：' | cut -d'：' -f2)" \
                   --arg text "$(echo "$ISSUE_BODY" | grep '内容：' | cut -d'：' -f2)" \
                   '. += [{"author": $author, "text": $text}]' data.json > tmp.json
                mv tmp.json data.json
            - name: Commit changes
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add data.json
                git commit -m "Update JSON from Issue #${{ github.event.issue.number }}"
                git push
